name: Deploy Static Site to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1.1.1'
        with:
          project_id: 'cdtest-406103'
          install_components: 'beta'

      - name: Build Docker image
        run: |
          docker build -t static-site .

      - name: Configure Docker and push image
        run: |
          gcloud auth configure-docker
          docker tag static-site gcr.io/cdtest-406103/static-site
          docker push gcr.io/cdtest-406103/static-site

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy static-site-service \
            --image=gcr.io/cdtest-406103/static-site \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
